### ISSUE TITLE
Xdrip+ Fitbit Versa error E404

### ISSUE THREAD

**Issue by KataCyber** [Rytiggy/Glance#99]
Hi! Watch work,s more than 10 days perfectly. But now already 2 day's data error E404 on display. I even make factory reset to watch but nothing change :(   Glance set to xdrip.  Is there Xtrip somehow involved with this error. Any help? [Log file here](https://docs.google.com/document/d/1vcVgluVHkDjKDHC2lZfbbqFjBjHdV7G2UEilNuASDGI/edit?usp=drivesdk)

**Comment by ddellspe** [comment]
This is likely related to #97 and #98 it's actually something Fitbit broke in their most recent app update (3.9.1) they have it fixed in their new update (3.10) but haven't released it yet, you can go to 3.8 as a current backout plan, but it will force you to re-do all of the setup.

**Comment by KataCyber** [comment]
Thank you! 3.8 version works fine again :)

**Comment by edisiENt** [comment]
This e404 error from Xdrip to Glance on Fitbit Versa still exists on Fitbit Android v3.11

**Comment by dennisandis** [comment]
This is also happening with 3.12.1 :(

**Comment by MichelaBelluta** [comment]
Help! I'm keep having the e404 error pn fitbit versa 2 despite trying all the troubleshooting I've found here. Im using xdrip

**Comment by MasterPlexus** [comment]
Also for me. Since 3 days no values available. Only 404

**Comment by MasterPlexus** [comment]
Fitbit app was updated at 22.7. may it was Brocken there?

**Comment by edisiENt** [comment]
Yes, the fitbit android app release on 22/July broke http communication with the fitibt device.  Reverting to a prior version of the android app eliminates the issue.  

 

See this topic in the fitbit community for guidance on how to revert to an prior version of the android app:  https://community.fitbit.com/t5/Android-App/Glance-clock-face-used-by-Diabetics-not-working/m-p/5199604/highlight/true#M159366
